/*
 * SprinkWord — daily 5-letter answers (fire sprinkler / fire protection themed)
 * ----------------------------------------------------------------------------
 * One word per day, chosen deterministically by date. Each entry: { w, hint }.
 *   - w MUST be 5 letters, A-Z, uppercase, a real word (validated against
 *     sprinkword-dictionary.js).
 *   - hint is a cryptic, riddle-style clue (shown on the 💡 button) — meant to
 *     be ambiguous and a little funny, NOT a giveaway.
 * Order sets the daily sequence (entry 0 = puzzle #1).
 * Tip for testing difficulty: open  sprinkword.html?n=3  (puzzle number) or
 *   sprinkword.html?word=PITOT  to preview any word without touching your streak.
 */
window.SPRINKWORD_ANSWERS = [
  // --- sprinkler system parts & fittings ---
  { w: "RISER", hint: "I get up early and never lie back down. Buildings keep one in the stairwell." },
  { w: "VALVE", hint: "An open-and-shut case. Your heart keeps a few of me." },
  { w: "DRAIN", hint: "The opposite of gain, and what Mondays do to the soul." },
  { w: "ELBOW", hint: "Apply grease to turn the corner. Found on your arm and your pipe — please don't lick." },
  { w: "GAUGE", hint: "A vowel pile-up that tattles on your pressure." },
  { w: "FLUSH", hint: "Royalty in poker, relief in plumbing — either way, things get moving." },
  { w: "UNION", hint: "Strength in numbers, or two pipes that agreed to part on good terms." },
  { w: "CROSS", hint: "Grumpy, or a four-way intersection that never installed a light." },
  { w: "SPRAY", hint: "Tan in a can, or what I do the moment things heat up." },
  { w: "HEADS", hint: "Tails' eternal rival, and the bits that actually do the squirting." },
  { w: "BULBS", hint: "Edison made one kind; mine are full of colored liquid and hate the heat." },
  { w: "FUSED", hint: "Totally blew it — or got bonded the hard way, with heat." },
  { w: "GLASS", hint: "Half empty or half full, I shatter under pressure. Literally." },
  { w: "PRIME", hint: "Amazon ships it, mathematicians adore it, pumps can't start without it." },
  { w: "PURGE", hint: "A spring-cleaning for your pipes. Sounds unpleasant on purpose." },
  { w: "TRIPS", hint: "Vacations — or what a clumsy dry valve takes the instant a sprinkler opens." },
  { w: "MAINS", hint: "The big shots of the pipe world. Also a New England state, slightly misspelled." },
  { w: "PUMPS", hint: "Footwear or muscle — either way, they raise things up." },
  { w: "TANKS", hint: "A thank-you with no manners, or where reserve water lounges." },
  { w: "HOSES", hint: "Firefighters wrangle them; gardeners trip over them." },
  { w: "MISTS", hint: "Almost missed, but wetter. A fog with ambitions." },
  { w: "FOAMS", hint: "What an angry latte and a flammable-liquid fire have in common." },
  { w: "AGENT", hint: "007, or the stuff that actually does the firefighting." },
  { w: "SPOOL", hint: "Thread's home, or a stubby length of pipe with delusions of grandeur." },
  { w: "BRACE", hint: "Yourself. Or the thing that keeps pipe calm during an earthquake." },
  { w: "CLAMP", hint: "...down. I grip pipe and bad moods with equal force." },
  { w: "JOINT", hint: "A knee, a dive bar, or where two pipes finally shake hands." },
  { w: "WELDS", hint: "Where metal marries metal. No minister required." },
  { w: "BOLTS", hint: "Lightning does it, horses do it, and I keep flanges from breaking up." },
  { w: "SEALS", hint: "They clap at the zoo, and they keep your joints from weeping." },
  { w: "PLUGS", hint: "Shameless self-promotion, or what corks the end of a pipe." },
  { w: "FEEDS", hint: "What you do to a hungry baby — and to a cross main." },
  { w: "LOOPS", hint: "A cereal shape, a coaster trick, or pipe that comes full circle." },
  { w: "GRIDS", hint: "Off-the-____ living, or a very tidy network of mains and branches." },
  { w: "ZONES", hint: "Out in left field, or the slices a system is carved into." },
  { w: "PIPES", hint: "Bagpipers squeeze them, plumbers love them, water rides inside." },
  { w: "STEEL", hint: "Man of ____, and the black metal your pipe probably is." },
  { w: "BRASS", hint: "The bold, the band section, and a shiny little fitting." },
  { w: "CHECK", hint: "The restaurant bill, a chess threat, or a valve that only lets water go one way." },
  { w: "WAFER", hint: "Communion-thin, and the valve squeezed between two flanges." },
  { w: "SWING", hint: "A playground favorite, or a check valve with a little hinged door." },
  { w: "TRIMS", hint: "A haircut, or all the gauges and gizmos dressing up a valve." },
  { w: "PITOT", hint: "Sounds like someone who flies planes; really just pokes into the flow to read it." },
  { w: "SUMPS", hint: "Grumpy without the 'gr', and a pit where stray water collects." },
  { w: "BENDS", hint: "Divers dread them; pipe just rolls with them around the corner." },
  { w: "ALARM", hint: "Your 6 a.m. nemesis, and what flowing water trips." },
  // --- fire & combustion ---
  { w: "FLAME", hint: "An old ____ (the ex), or the dancing thing you're trying to drown." },
  { w: "EMBER", hint: "November is hiding one. A coal that refuses to clock out." },
  { w: "BLAZE", hint: "A trail you set, or a fire that's clearly showing off." },
  { w: "SMOKE", hint: "Where there's me, there's fire — the detectors will back me up." },
  { w: "TORCH", hint: "Carry one for someone, or use one to cause real trouble." },
  { w: "BURNS", hint: "A comedy roast, a Scottish poet, or what fire does for a living." },
  { w: "SINGE", hint: "A haircut gone wrong; a fire's polite little warning nibble." },
  { w: "ARSON", hint: "Rearrange a 'son' with a match and bad intentions." },
  { w: "DOUSE", hint: "Drench it thoroughly. Rhymes with the place you live." },
  { w: "CHARS", hint: "What fire does to a forgotten steak." },
  { w: "SCALD", hint: "The threat hidden in hot coffee and an angry kettle." },
  { w: "ASHES", hint: "What's left when the fire clocks out — also a cricket trophy." },
  // --- storage / commodity / design ---
  { w: "CLASS", hint: "Where you napped through algebra, or how a commodity gets ranked I–IV." },
  { w: "GROUP", hint: "A chat, a band, or how plastics get sorted A, B, and C." },
  { w: "RACKS", hint: "Pool-table gear, or steel shelves stacked toward the heavens." },
  { w: "AISLE", hint: "The bride walks down it; firefighters need it between the storage rows." },
  { w: "SHELF", hint: "Where books retire; the solid kind rudely blocks water below." },
  { w: "BALES", hint: "Hay's favorite shape — compressed, and far too eager to burn." },
  { w: "DRUMS", hint: "A band's heartbeat, or 55 gallons of trouble." },
  { w: "STORE", hint: "Where you shop, or what a warehouse does for a living." },
  { w: "PILES", hint: "An uncomfortable medical word — or goods stacked without a rack." },
  { w: "FLUES", hint: "Sounds like the sickness; really the gaps a fire loves to climb." },
  { w: "DENSE", hint: "Not the sharpest crayon, and how tightly the storage is packed." },
  { w: "AREAS", hint: "Plural of a region; the most demanding one is your design bullseye." },
  // --- building & structure ---
  { w: "STUDS", hint: "Hunky fellows, or the vertical bones inside a wall." },
  { w: "BEAMS", hint: "Grins from ear to ear, and holds the roof up overhead." },
  { w: "JOIST", hint: "Rhymes with 'moist' (apologies) and quietly supports your floor." },
  { w: "TRUSS", hint: "A triangle gang that spans a roof and never breaks trust." },
  { w: "FLOOR", hint: "A knockout punch sends you here; storage just sits on it." },
  { w: "WALLS", hint: "Pink Floyd built one. They box you in and cut the spray short." },
  { w: "DECKS", hint: "Card stacks, ship tops, or the roof surface right above you." },
  { w: "EAVES", hint: "Sounds like a name; really just hangs off the roof eavesdropping." },
  { w: "VENTS", hint: "Where you let off steam, or roof holes that bleed smoke and heat." },
  { w: "DUCTS", hint: "Quack-alikes that haul air around and block the sprinkler spray." },
  { w: "ATTIC", hint: "Where the holiday boxes and old secrets live, just under the roof." },
  { w: "CHUTE", hint: "Bless you? No — a slide that sends trash between floors." },
  { w: "SLABS", hint: "Ribs at the BBQ, or the poured concrete you stand on." },
  // --- water & hydraulics ---
  { w: "WATER", hint: "H-two-oh my. The original firefighter." },
  { w: "FLOWS", hint: "Go with the ____, and what a switch senses to ring the bell." },
  { w: "STAND", hint: "Take a ____, or the 'pipe' that feeds the firefighters' hoses." },
];
