/*
 * SprinkWord — daily 5-letter answers (fire sprinkler / fire protection themed)
 * ----------------------------------------------------------------------------
 * One word per day, chosen deterministically by date so everyone gets the same
 * puzzle. Each entry: { w: "WORD", hint: "a clue/riddle" }.
 *   - w MUST be exactly 5 letters, A-Z, uppercase, a real word (validated
 *     against sprinkword-dictionary.js), and reasonably guessable.
 *   - hint is shown when the player taps the 💡 button.
 * Add more to extend the rotation (it repeats once it runs out). Order sets the
 * daily sequence (entry 0 = puzzle #1).
 */
window.SPRINKWORD_ANSWERS = [
  // --- sprinkler system parts & fittings ---
  { w: "RISER", hint: "The vertical pipe where a sprinkler system begins its climb." },
  { w: "VALVE", hint: "Open it or close it — it controls the flow." },
  { w: "DRAIN", hint: "Where the water goes when you empty the system." },
  { w: "ELBOW", hint: "A 90° turn in the pipe, named for part of your arm." },
  { w: "GAUGE", hint: "It reads the system pressure at a glance." },
  { w: "FLUSH", hint: "Clear the line of debris with a rush of water." },
  { w: "UNION", hint: "A fitting that joins two pipes and can be taken apart." },
  { w: "CROSS", hint: "A fitting with four openings — and what you do at a street corner." },
  { w: "SPRAY", hint: "What a sprinkler does to a fire." },
  { w: "HEADS", hint: "The business end of the system — sprinkler ____." },
  { w: "BULBS", hint: "Glass ____ hold the liquid that bursts in a fire." },
  { w: "FUSED", hint: "A solder link that has melted — or two things joined by heat." },
  { w: "GLASS", hint: "The frangible bulb material that shatters at temperature." },
  { w: "PRIME", hint: "Get a pump ready — or a number divisible only by itself and one." },
  { w: "PURGE", hint: "Force the air or water out of the line." },
  { w: "TRIPS", hint: "What a dry-pipe valve does when a sprinkler opens." },
  { w: "MAINS", hint: "The big supply pipes that feed the branch lines." },
  { w: "PUMPS", hint: "Fire ____ boost the water pressure." },
  { w: "TANKS", hint: "Storage vessels that hold reserve water." },
  { w: "HOSES", hint: "Firefighters connect these to a standpipe." },
  { w: "MISTS", hint: "Fine water ____ — a fog of tiny droplets." },
  { w: "FOAMS", hint: "Concentrate-and-water blankets for flammable liquids." },
  { w: "AGENT", hint: "The extinguishing ____ — or a secret one." },
  { w: "SPOOL", hint: "A short pipe piece — or what thread winds onto." },
  { w: "BRACE", hint: "Seismic sway ____ keeps pipe steady in a quake." },
  { w: "CLAMP", hint: "A device that grips and holds pipe tight." },
  { w: "JOINT", hint: "The place where two pipes meet." },
  { w: "WELDS", hint: "Heat-fused metal connections." },
  { w: "BOLTS", hint: "Threaded fasteners for flanged connections." },
  { w: "SEALS", hint: "Gaskets that keep joints watertight." },
  { w: "PLUGS", hint: "Threaded fittings that close off an opening." },
  { w: "FEEDS", hint: "A ____ main supplies the cross mains." },
  { w: "LOOPS", hint: "Gridded systems use these closed pipe ____." },
  { w: "GRIDS", hint: "A network layout of cross mains and branch lines." },
  { w: "ZONES", hint: "Areas a system is divided into for control." },
  { w: "PIPES", hint: "What carries the water." },
  { w: "STEEL", hint: "Common black or galvanized pipe metal." },
  { w: "BRASS", hint: "Yellow alloy used for many sprinkler fittings." },
  { w: "CHECK", hint: "A one-way ____ valve stops backflow." },
  { w: "WAFER", hint: "A thin ____ valve fits between two flanges." },
  { w: "SWING", hint: "A ____ check valve has a hinged disc." },
  { w: "TRIMS", hint: "Valve ____ — the gauges, drains, and fittings around it." },
  { w: "PITOT", hint: "A tube or gauge that reads flow at a hydrant." },
  { w: "SUMPS", hint: "Low pits that collect drained water." },
  { w: "BENDS", hint: "Gentle curves in a run of pipe." },
  { w: "ALARM", hint: "The bell or signal that says water is flowing." },
  // --- fire & combustion ---
  { w: "FLAME", hint: "The visible, dancing part of a fire." },
  { w: "EMBER", hint: "A glowing piece of coal left in the ashes." },
  { w: "BLAZE", hint: "A large, roaring fire." },
  { w: "SMOKE", hint: "What detectors sense before the flames arrive." },
  { w: "TORCH", hint: "A handheld flame — or to set alight." },
  { w: "BURNS", hint: "What fire does to fuel or skin." },
  { w: "SINGE", hint: "To burn lightly at the edges." },
  { w: "ARSON", hint: "The crime of deliberately setting a fire." },
  { w: "DOUSE", hint: "To drench and put out." },
  { w: "CHARS", hint: "Burns something to blackened carbon." },
  { w: "SCALD", hint: "A burn from hot liquid or steam." },
  { w: "ASHES", hint: "Gray dust left after the fire dies." },
  // --- storage / commodity / design ---
  { w: "CLASS", hint: "Commodities are sorted into ____ I through IV." },
  { w: "GROUP", hint: "Plastics are sorted into ____ A, B, and C." },
  { w: "RACKS", hint: "Steel storage ____ hold pallets in rows." },
  { w: "AISLE", hint: "The walkway between storage racks." },
  { w: "SHELF", hint: "A solid ____ can block water from reaching below." },
  { w: "BALES", hint: "Compressed bundles of cotton or paper." },
  { w: "DRUMS", hint: "Fifty-five-gallon barrels of liquid." },
  { w: "STORE", hint: "To keep goods in a warehouse — or the shop itself." },
  { w: "PILES", hint: "Solid-____ storage stacks goods without racks." },
  { w: "FLUES", hint: "Vertical spaces between stored loads that let fire climb." },
  { w: "DENSE", hint: "Tightly packed — like high-piled storage." },
  { w: "AREAS", hint: "The design ____ is the most remote group of sprinklers." },
  // --- building & structure ---
  { w: "STUDS", hint: "Vertical framing members inside a wall." },
  { w: "BEAMS", hint: "Horizontal structural members running overhead." },
  { w: "JOIST", hint: "A repeated framing member supporting a floor or roof." },
  { w: "TRUSS", hint: "A triangulated framework spanning a roof." },
  { w: "FLOOR", hint: "You stand on it; storage sits on it." },
  { w: "WALLS", hint: "They bound a room and limit sprinkler throw." },
  { w: "DECKS", hint: "Roof ____ — the surface sprinklers protect below." },
  { w: "EAVES", hint: "The overhanging lower edge of a roof." },
  { w: "VENTS", hint: "Roof openings that release smoke and heat." },
  { w: "DUCTS", hint: "HVAC channels that can obstruct sprinkler spray." },
  { w: "ATTIC", hint: "The space just below the roof." },
  { w: "CHUTE", hint: "A trash or laundry ____ runs between floors." },
  { w: "SLABS", hint: "Poured concrete floor ____." },
  // --- water & hydraulics ---
  { w: "WATER", hint: "The most common extinguishing agent." },
  { w: "FLOWS", hint: "What the ____ switch detects to sound the alarm." },
  { w: "STAND", hint: "A ____pipe serves hose connections in a building." },
];
